### ISSUE TITLE
Repeating styles

### ISSUE THREAD

**Issue by ghost** [sudhoffm/prj-rev-bwfs-dasmoto#5]
https://github.com/sudhoffm/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/Resources/CSS/style.css#L11-L28

These three rules are all mostly the same. Try to put the shared styles into a single CSS rule with multiple selectors (or a more general selector).

```css
.brushes, .frames, .paint {
        font-size: 32px;
	font-weight: bold;
	color: white;
}
```
